[build]
publish = "playground/dist"
command = "pnpm run deploy"

[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/play/index.html"
status = 200

[[redirects]]
from = "/talk/*"
to = "/talk/index.html"
status = 200
