packages:
  - playground
  - docs
  - talk
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^3.11.2
  '@antfu/ni': ^0.23.1
  '@iconify-json/akar-icons': ^1.2.1
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/fluent-emoji': ^1.2.1
  '@iconify-json/logos': ^1.2.3
  '@iconify/utils': ^2.1.33
  '@slidev/cli': 0.49.23
  '@slidev/client': 0.49.23
  '@types/node': ^22.10.1
  '@types/prettier': ^3.0.0
  '@unocss/preset-mini': ^0.65.0-beta.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.0.0
  '@vueuse/shared': ^12.0.0
  bumpp: ^9.8.1
  chart.js: ^4.4.7
  eslint: ^9.16.0
  esno: ^4.8.0
  lint-staged: ^15.2.10
  pnpm: ^9.14.4
  prettier: ^3.4.1
  rimraf: ^6.0.1
  shiki: ^1.24.0
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  typescript: ^5.7.2
  unbuild: ^2.0.0
  unocss: ^0.65.0-beta.3
  unocss-preset-useful: ^0.8.0
  unplugin-auto-import: ^0.18.6
  unplugin-vue-components: ^0.27.5
  vite: ^6.0.1
  vitest: ^2.1.6
  vue: ^3.5.13
  vue-tsc: ^2.1.10
