packages:
  - playground
  - docs
  - talk
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.2.0
  '@antfu/ni': ^23.3.1
  '@arethetypeswrong/cli': 0.17.1
  '@iconify-json/akar-icons': ^1.2.2
  '@iconify-json/carbon': ^1.2.6
  '@iconify-json/fluent-emoji': ^1.2.3
  '@iconify-json/logos': ^1.2.4
  '@iconify/utils': ^2.3.0
  '@slidev/cli': 0.49.23
  '@slidev/client': 0.49.23
  '@types/node': ^22.13.1
  '@types/prettier': ^3.0.0
  '@unocss/preset-mini': ^65.4.3
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.5.0
  '@vueuse/shared': ^12.5.0
  bumpp: ^10.0.3
  chart.js: ^4.4.7
  eslint: ^9.20.1
  esno: ^4.8.0
  lint-staged: ^15.4.3
  pnpm: ^10.3.0
  prettier: ^3.5.0
  rimraf: ^6.0.1
  shiki: ^2.3.2
  simple-git-hooks: ^2.11.1
  taze: ^18.5.0
  typescript: ^5.7.2
  unbuild: ^3.3.1
  unocss: ^65.4.3
  unocss-preset-useful: ^0.9.2
  unplugin-auto-import: ^19.0.0
  unplugin-vue-components: ^28.0.0
  vite: ^6.1.0
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-tsc: ^2.2.0
