packages:
  - playground
  - docs
  - talk
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^2.24.1
  '@antfu/ni': ^0.22.0
  '@iconify-json/akar-icons': ^1.1.24
  '@iconify-json/carbon': ^1.1.36
  '@iconify-json/fluent-emoji': ^1.1.18
  '@iconify-json/logos': ^1.1.43
  '@iconify/utils': ^2.1.29
  '@slidev/cli': 0.49.23
  '@slidev/client': 0.49.23
  '@types/chroma-js': ^2.4.4
  '@types/node': ^22.1.0
  '@unocss/preset-mini': ^0.61.9
  '@vitejs/plugin-vue': ^5.1.2
  '@vueuse/core': ^10.11.0
  '@vueuse/shared': ^10.11.0
  bumpp: ^9.4.2
  chart.js: ^4.4.3
  chroma-js: ^2.6.0
  eslint: ^9.8.0
  esno: ^4.7.0
  lint-staged: ^15.2.7
  pnpm: ^9.6.0
  rimraf: ^6.0.1
  simple-git-hooks: ^2.11.1
  typescript: ^5.5.4
  unbuild: ^2.0.0
  unocss: ^0.61.9
  unocss-preset-useful: ^0.4.2
  unplugin-auto-import: ^0.18.2
  unplugin-vue-components: ^0.27.3
  vite: ^5.3.5
  vitest: ^2.0.5
  vue: ^3.4.35
  vue-tsc: ^2.0.29
