name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Set node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies 📦️
        run: pnpm i

      - name: PNPM build ٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ
        run: pnpm build

      - name: Publish to NPM 🚀
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      # - run: npx changelogithub
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
